// Export utilities for PDF, CSV, and JSON

export const exportToPDF = async (results) => {
  try {
    // For a real implementation, you would use jsPDF and html2canvas
    // This is a placeholder that creates a simple text file
    const content = `
      VIRO-AI ANALYSIS REPORT
      ========================
      
      Virus: ${results.virus}
      Protein: ${results.protein_name}
      Date: ${new Date(results.timestamp).toLocaleString()}
      
      DEADLINESS SCORE: ${results.deadliness_score.overall_score}/100
      Risk Level: ${results.deadliness_score.risk_level}
      
      TOP DRUG CANDIDATES:
      ${results.top_candidates?.slice(0, 5).map((drug, i) => 
        `${i + 1}. ${drug.drug_name} - Score: ${drug.predicted_affinity.toFixed(2)} - IC50: ${drug.estimated_ic50_nm.toFixed(1)} nM`
      ).join('\n      ')}
      
      SCORE BREAKDOWN:
      - Transmissibility: ${results.deadliness_score.transmissibility}/100
      - Immune Evasion: ${results.deadliness_score.immune_evasion}/100
      - Mortality Rate: ${results.deadliness_score.mortality_rate}/100
      - Infection Severity: ${results.deadliness_score.infection_severity}/100
      
      Drugs Screened: ${results.drugs_screened}
      Processing Time: ${results.processing_time_ms}ms
      
      ---
      Generated by Viro-AI v1.0
      For research and educational purposes only
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    downloadBlob(blob, `viroai_report_${results.virus}_${Date.now()}.txt`);
    
    return true;
  } catch (error) {
    console.error('PDF export failed:', error);
    throw new Error('Failed to export PDF');
  }
};

export const exportToCSV = (results) => {
  try {
    // Create CSV header
    const headers = ['Rank', 'Drug Name', 'Drug ID', 'Binding Score', 'IC50 (nM)', 'Binding Strength', 'Molecular Weight', 'LogP'];
    
    // Create CSV rows
    const rows = results.top_candidates?.map(drug => [
      drug.rank,
      drug.drug_name,
      drug.drug_id,
      drug.predicted_affinity.toFixed(4),
      drug.estimated_ic50_nm.toFixed(2),
      drug.binding_strength,
      drug.molecular_weight.toFixed(2),
      drug.logP.toFixed(2),
    ]);

    // Combine headers and rows
    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.join(','))
    ].join('\n');

    // Add metadata as comments
    const metadata = `# Viro-AI Analysis Results
# Virus: ${results.virus}
# Protein: ${results.protein_name}
# Date: ${new Date(results.timestamp).toLocaleString()}
# Deadliness Score: ${results.deadliness_score.overall_score}/100
# Drugs Screened: ${results.drugs_screened}
#
`;

    const fullContent = metadata + csvContent;
    const blob = new Blob([fullContent], { type: 'text/csv' });
    downloadBlob(blob, `viroai_drugs_${results.virus}_${Date.now()}.csv`);
    
    return true;
  } catch (error) {
    console.error('CSV export failed:', error);
    throw new Error('Failed to export CSV');
  }
};

export const exportToJSON = (results) => {
  try {
    const jsonStr = JSON.stringify(results, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/json' });
    downloadBlob(blob, `viroai_results_${results.virus}_${Date.now()}.json`);
    return true;
  } catch (error) {
    console.error('JSON export failed:', error);
    throw new Error('Failed to export JSON');
  }
};

// Helper function to download blob
const downloadBlob = (blob, filename) => {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// Share functionality
export const shareResults = async (results) => {
  const shareData = {
    title: `Viro-AI Analysis: ${results.virus}`,
    text: `Check out this viral analysis: ${results.virus} (Deadliness: ${results.deadliness_score.overall_score}/100)`,
    url: window.location.href,
  };

  try {
    if (navigator.share) {
      await navigator.share(shareData);
      return true;
    } else {
      // Fallback: copy link to clipboard
      await navigator.clipboard.writeText(window.location.href);
      return true;
    }
  } catch (error) {
    console.error('Share failed:', error);
    throw new Error('Failed to share results');
  }
};


