import React from 'react';

const DescriptionCard = ({ drugData }) => {
  const drug = drugData?.top_candidates?.[0] || {};
  const virusName = drugData?.virus || 'Virus';
  const proteinName = drugData?.protein_name || 'viral protein';
  const deadliness = drugData?.deadliness_score || {};

  // Convert binding affinity (0-1) to percentage
  const bindingScore = drug.predicted_affinity ? (drug.predicted_affinity * 100).toFixed(0) : 'N/A';
  const ic50 = drug.estimated_ic50_nm ? drug.estimated_ic50_nm.toFixed(1) : 'N/A';

  return (
    <div className="description-card">
      <h3>Drug Analysis & Target Information</h3>
      
      {/* Deadliness Score Banner */}
      {deadliness.overall_score && (
        <div style={{
          backgroundColor: deadliness.risk_level === 'CRITICAL' ? '#e74c3c' :
                          deadliness.risk_level === 'HIGH' ? '#e67e22' :
                          deadliness.risk_level === 'MEDIUM' ? '#f39c12' : '#2ecc71',
          color: 'white',
          padding: '0.75rem',
          borderRadius: '10px',
          marginBottom: '1rem',
          textAlign: 'center'
        }}>
          <strong>Viral Threat: {deadliness.overall_score}/100</strong> • {deadliness.risk_level}
        </div>
      )}
      
      <div className="drug-description">
        <p>
          <strong>Target Virus:</strong> {virusName}
        </p>
        <p>
          <strong>Target Protein:</strong> {proteinName}
        </p>
        
        <p>
          <strong>Predicted Binding Affinity:</strong> {bindingScore}% 
          {drug.binding_strength && ` (${drug.binding_strength} binding)`}
        </p>
        
        <p>
          <strong>Estimated IC50:</strong> {ic50} nM
          {drug.estimated_ic50_nm && drug.estimated_ic50_nm < 100 && ' (Highly potent)'}
        </p>
        
        <p>
          <strong>Mechanism:</strong> This drug targets the {proteinName} of {virusName}, 
          inhibiting viral replication by binding to critical active sites. The AI model 
          predicts strong binding affinity based on molecular features and structural compatibility.
        </p>
        
        {deadliness.transmissibility && (
          <p>
            <strong>Viral Properties:</strong> Transmissibility: {deadliness.transmissibility}%, 
            Immune Evasion: {deadliness.immune_evasion}%, 
            Mortality: {deadliness.mortality_rate}%
          </p>
        )}
        
        <p style={{ fontSize: '0.9rem', color: '#7f8c8d', marginTop: '1rem' }}>
          💡 This recommendation is generated by Viro-AI's machine learning model trained on 
          {drugData?.drugs_screened || 'validated'} drug-virus interactions.
        </p>
      </div>
    </div>
  );
};

export default DescriptionCard;

