-- Migration: User Profile Enhancements
-- Created: 2025-11-20
-- Description: Add enhanced profile fields for user management

ALTER TABLE users ADD COLUMN IF NOT EXISTS qualification VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS occupation VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS professional_summary TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS skills JSON;
ALTER TABLE users ADD COLUMN IF NOT EXISTS experience JSON;
ALTER TABLE users ADD COLUMN IF NOT EXISTS publications JSON;
ALTER TABLE users ADD COLUMN IF NOT EXISTS awards JSON;
ALTER TABLE users ADD COLUMN IF NOT EXISTS social_links JSON;
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

