@echo off
echo ========================================
echo   ViroBot AI Chatbot Setup
echo ========================================
echo.

echo Creating .env file with your API key...
echo.

(
echo # Viro-AI Environment Variables
echo # Auto-generated by SETUP_CHATBOT.bat
echo.
echo # === AI Chatbot Configuration ===
echo GEMINI_API_KEY=AIzaSyCQdCCU1vBJ13mWZflM3mCb0pG64drjc0o
echo.
echo # === API Configuration ===
echo API_HOST=0.0.0.0
echo API_PORT=8000
echo.
echo # === Frontend Configuration ===
echo VITE_API_BASE_URL=http://localhost:8000
) > .env

echo ========================================
echo   SUCCESS! .env file created
echo ========================================
echo.
echo Your API key has been saved securely!
echo.
echo Next steps:
echo 1. Restart your backend server
echo 2. Look for: "Loaded environment variables"
echo 3. Test ViroBot by logging in!
echo.
echo ========================================
echo.
pause

